name: C/C++ CI

on:
  push:
    branches: [ "br_cpp_dev" ]
  pull_request:
    branches: [ "br_cpp_dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
